# Generated by Django 5.2.5 on 2025-08-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='olingan_sana',
        ),
        migrations.RemoveField(
            model_name='record',
            name='qaytarish_sana',
        ),
    ]
