# Generated by Django 5.2.5 on 2025-08-20 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_record_olingan_sana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='olingan_sana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateTimeField(null=True),
        ),
    ]
