# Generated by Django 5.2.5 on 2025-08-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_record_olingan_sana_record_qaytarish_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.muallif'),
            preserve_default=False,
        ),
    ]
