# Generated by Django 5.2.5 on 2025-08-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_kitob_muallif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kitob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kitob'),
            preserve_default=False,
        ),
    ]
